// Code generated by protoc-gen-go. DO NOT EDIT.
// source: life360_account_deleted_v1.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Life360AccountDeleted struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Life360AccountDeleted) Reset()         { *m = Life360AccountDeleted{} }
func (m *Life360AccountDeleted) String() string { return proto.CompactTextString(m) }
func (*Life360AccountDeleted) ProtoMessage()    {}
func (*Life360AccountDeleted) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6d779d395a331bb, []int{0}
}

func (m *Life360AccountDeleted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Life360AccountDeleted.Unmarshal(m, b)
}
func (m *Life360AccountDeleted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Life360AccountDeleted.Marshal(b, m, deterministic)
}
func (m *Life360AccountDeleted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Life360AccountDeleted.Merge(m, src)
}
func (m *Life360AccountDeleted) XXX_Size() int {
	return xxx_messageInfo_Life360AccountDeleted.Size(m)
}
func (m *Life360AccountDeleted) XXX_DiscardUnknown() {
	xxx_messageInfo_Life360AccountDeleted.DiscardUnknown(m)
}

var xxx_messageInfo_Life360AccountDeleted proto.InternalMessageInfo

func (m *Life360AccountDeleted) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Life360AccountDeleted) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func init() {
	proto.RegisterType((*Life360AccountDeleted)(nil), "main.Life360AccountDeleted")
}

func init() { proto.RegisterFile("life360_account_deleted_v1.proto", fileDescriptor_b6d779d395a331bb) }

var fileDescriptor_b6d779d395a331bb = []byte{
	// 114 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xc8, 0xc9, 0x4c, 0x4b,
	0x35, 0x36, 0x33, 0x88, 0x4f, 0x4c, 0x4e, 0xce, 0x2f, 0xcd, 0x2b, 0x89, 0x4f, 0x49, 0xcd, 0x49,
	0x2d, 0x49, 0x4d, 0x89, 0x2f, 0x33, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d,
	0xcc, 0xcc, 0x53, 0x72, 0xe7, 0x12, 0xf5, 0x81, 0xa8, 0x74, 0x84, 0x28, 0x74, 0x81, 0xa8, 0x13,
	0x12, 0xe3, 0x62, 0x2b, 0x2d, 0x4e, 0x2d, 0xf2, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c,
	0x82, 0xf2, 0x40, 0xe2, 0x45, 0xa9, 0x89, 0xc5, 0xf9, 0x79, 0x12, 0x4c, 0x10, 0x71, 0x08, 0x2f,
	0x89, 0x0d, 0x6c, 0xaa, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x49, 0x67, 0x75, 0xff, 0x79, 0x00,
	0x00, 0x00,
}
